version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.7
    restart: on-failure
    networks:
      - kanthor
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - '8123:8123'
      - '9000:9000'

  uptrace:
    image: 'uptrace/uptrace:1.6.2'
    restart: on-failure
    networks:
      - kanthor
    volumes:
      - ./docker/.uptrace/uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - '14317:14317'
      - '14318:14318'

networks:
  network1:
    name: kanthor
    external: true